name: Create Release

on: 
  workflow_call:
    inputs:
      ubuntu-version:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  create-release:
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    runs-on: ${{ inputs.ubuntu-version }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Create Release'
      run: 'gh release create --verify-tag ${{ inputs.tag }}'
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
