name: Deploy Docker Image

on: 
  workflow_call:
    inputs:
      ubuntu-version:
        required: true
        type: string
      tag:
        required: true
        type: string
      image-name:
        required: true
        type: string
jobs:
  deploy-docker-image:
    permissions:
      packages: write
    runs-on: ${{ inputs.ubuntu-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./alpine-linux.dockerfile
          push: true
          tags: ghcr.io/atomic-works/${{ inputs.image-name }}:development, ghcr.io/atomic-works/${{ inputs.image-name }}:${{ inputs.tag }}
