name: Validate Target Branch

on:
  workflow_call:
    inputs:
      ubuntu-version:
        required: true
        type: string
      PR-branch-name:
        required: true
        type: string
      base-branch-name:
        required: true
        type: string
     

jobs:
  validate-target-branch:
    runs-on: ${{ inputs.ubuntu-version }}
    steps:
    - name: Validate Target Branch
      id: validate-target-branch
      run: |
        if \
        [[ \
          "${{ inputs.PR-branch-name }} ==  "test" && "${{ inputs.base-branch-name }}" != "production"   || \
          "${{ inputs.PR-branch-name }}" ==  "development" && "${{ inputs.base-branch-name }}" != "test" || \
          "${{ inputs.PR-branch-name }} == "production"                                                  || \
          "${{ inputs.base-branch-name }}" != "development"                                                 \
        ]]; then
          exit 1
        else
          exit 0
        fi
